import { NeptuneLogo, NeptuneLogoText } from "@svg";
import Head from "next/head";
import Link from "next/link";

const Header = () => {
  return (
    <div>
      <Head>
        <title>NeptuneMutual - Cover Fee Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full px-4 sm:px-8 py-4 text-white bg-prim-blue">
        <Link href="/">
          <a className="block w-min">
            <div className="flex items-center gap-2">
              <NeptuneLogo />
              <NeptuneLogoText height={35} />
            </div>
          </a>
        </Link>
      </div>
    </div>
  );
};

export default Header;
